baseurl      = "https://blog.ehmiiz.tech"
title        = "Ehmiiz.Tech - A book blog"
languageCode = "en-us"
theme        = "hello-friend"
paginate     = 10

# disqusShortname = "https-blog-ehmiiz-tech"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Be sure to check out the posts while your here"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "blog.ehmiiz.tech"
    subtitle = ""
    keywords = ""

    [languages.en.params.logo]
      logoText = "blog.ehmiiz.tech"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "/cv"

[permalinks]
  posts = "/:title"

 [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/ehmiiz"
  [[params.social]]
    name = "github"
    url  = "https://github.com/ehmiiz"
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/emil-larsson-224552ba/"
